env:
  name: AndOps

network:
  name: gym_model
  num_state: 2
  num_action: 1
  discrete_action: False
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.168
  sigma_decay: 0.99
  learning_rate: 0.12
  offspring_num: 200