env:
  name: CartPole-v1
  max_step: 500
  pomdp: False

network:
  name: gym_model
  num_state: 4
  num_action: 2
  discrete_action: True
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.168
  sigma_decay: 0.9999
  learning_rate: 0.12
  offspring_num: 88