env:
  name: HalfCheetahBulletEnv-v0
  max_step: 500
  pomdp: False

network:
  name: gym_model
  num_state: 26
  num_action: 6
  discrete_action: False
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.168
  sigma_decay: 0.9999
  learning_rate: 0.087
  offspring_num: 121