env:
  name: waterworld
  max_step: None

network:
  name: gym_model
  num_state: 242
  num_action: 2
  discrete_action: False
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.15
  sigma_decay: 0.9999
  learning_rate: 0.08
  offspring_num: 240
  individual_play: False