env:
  name: UnityCollectApple
  max_step: 300
  pomdp: False

network:
  name: gym_model
  num_state: 6
  num_action: 2
  discrete_action: False
  gru: False

strategy:
  name : openai_es
  init_sigma: 0.17
  sigma_decay: 0.9999
  learning_rate: 0.1
  offspring_num: 11